### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by Dapid** [ManchesterBioinference/BranchedGP#11]
The tests have been failing since 9 months ago, probably some change made in GPflow. Is there any chance of it being updated? If not, do you have a list of known, working versions?

Thanks!

**Comment by sumonahmedUoM** [comment]
Hi, Sorry for your trouble. We have just updated the code compatible with the latest version(1.3.0) of gpflow.
Please clone the repository and try a new installation of the package. Please let us know if you have further issues.

**Comment by Dapid** [comment]
Thanks for the quick response!

The Travis build still fails:
 error: numpy 1.13.3 is installed but numpy<2.0,>=1.14.5 is required by {'tensorflow'}
The command "python setup.py install" failed and exited with 1 during .

The tests give five errors, five others run fine. Here is the traceback:

======================================================================
ERROR: test_pZ (testpZ_construct.TestpZ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/_settings.py", line 35, in __getattr__
    return self._cur_settings[name]
KeyError: 'tf_float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/gits/BranchedGP/testing/testpZ_construct.py", line 14, in test_pZ
    BP_tf = tf.placeholder(settings.tf_float, shape=[])
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/_settings.py", line 37, in __getattr__
    raise AttributeError("Unknown setting.")
AttributeError: Unknown setting.

**Comment by sumonahmedUoM** [comment]
It seems you are using tensorflow >= 1.13.1 which requires numpy >= 1.14.5 < 2.0. You need to update numpy for that. Some other packages may need to be updated.  
I have updated the test code, so it should work now. Please let us know how it goes.

**Comment by Dapid** [comment]
Thanks, that solved two errors, but there are still three more, I am sorry I missed them.

```
ERROR: test (testAssignment.TestSparseVariational)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/gits/BranchedGP/testing/testAssignment.py", line 63, in test
    ttestl, mul, varl = VBHelperFunctions.predictBranchingModel(m)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/BranchedGP/VBHelperFunctions.py", line 111, in predictBranchingModel
    mu, var = m.predict_f(Xtest)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 166, in autoflow_wrapper
    return _session_run(session, obj, store, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 204, in _session_run
    return session.run(store['result'], **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2, 1) for Tensor 'autoflow/AssignGP/predict_f/Placeholder:0', which has shape '(?, ?)'
======================================================================
ERROR: test (testObjective.TestObjectiveMin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/gits/BranchedGP/testing/testObjective.py", line 42, in test
    maxiter=50, priorConfidence=0.65, kervar=1., kerlen=1., likvar=0.01)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/BranchedGP/FitBranchingModel.py", line 107, in FitModel
    ttestl, mul, varl = VBHelperFunctions.predictBranchingModel(m)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/BranchedGP/VBHelperFunctions.py", line 111, in predictBranchingModel
    mu, var = m.predict_f(Xtest)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 166, in autoflow_wrapper
    return _session_run(session, obj, store, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 204, in _session_run
    return session.run(store['result'], **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2, 1) for Tensor 'autoflow/AssignGPSparse/predict_f/Placeholder:0', which has shape '(?, ?)'
======================================================================
ERROR: test (testSamplingAndPlotting.TestSamplingAndPlotting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/gits/BranchedGP/testing/testSamplingAndPlotting.py", line 38, in test
    maxiter=40, priorConfidence=0.80, M=10)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/BranchedGP/FitBranchingModel.py", line 107, in FitModel
    ttestl, mul, varl = VBHelperFunctions.predictBranchingModel(m)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/BranchedGP/VBHelperFunctions.py", line 111, in predictBranchingModel
    mu, var = m.predict_f(Xtest)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 166, in autoflow_wrapper
    return _session_run(session, obj, store, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/gpflow/decors.py", line 204, in _session_run
    return session.run(store['result'], **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 2, 1) for Tensor 'autoflow/AssignGPSparse/predict_f_1/Placeholder:0', which has shape '(?, ?)'
```

**Comment by sumonahmedUoM** [comment]
Hi, can you please try now. I got all the test successful:
[success] 47.35% testSamplingAndPlotting.TestSamplingAndPlotting.test: 823.7711s
[success] 29.64% testSparseToFullModel.TestSparseVariational.test_sparse: 515.7025s
[success] 15.09% testObjective.TestObjectiveMin.test: 262.5734s
[success] 2.34% testpZ_construct.TestpZ.test_pZ: 40.6756s
[success] 2.19% testAssignment.TestSparseVariational.test: 38.1267s
[success] 1.48% testKL.TestKL.test: 25.6736s
[success] 1.17% testpZ_construct.TestpZ.test_further: 20.3658s
[success] 0.74% testKernel.TestKernelSampling.test: 12.8765s
[success] 0.00% testTree.TestSparseVariational.test: 0.0170s
[success] 0.00% test_notebooks.TestNotebooks.test_all_notebooks: 0.0001s

**Comment by Dapid** [comment]
I am at commit c9131a0b9a037e6da491f56c76fb6b0ee074ec31:

Author: sumonahmedUoM <sumon.ahmed@postgrad.manchester.ac.uk>
Date:   Wed May 22 20:03:08 2019 +0100

    updating test files for gpflow 1.3.0

**Comment by sumonahmedUoM** [comment]
Yes. That is the final commit. 
I think the problem is with the python version. I am using python 3.5. I am trying to regenerate the same error using python 3.6. Probably python 3.6 is creating an extra dimension while generating test input. Allow me to investigate more, I will give an update by tomorrow.

**Comment by sumonahmedUoM** [comment]
I have pushed an update. It should work now. Please check and let us know.

**Comment by Dapid** [comment]
Thanks! It works now.

I have also made a synthetic, more compact example.

```
import numpy as np                                                                                                                                                                            
import pylab as plt                                                                                                                                                                           
                                                                                                                                                                                              
import BranchedGP                                                                                                                                                                             
                                                                                                                                                                                              
                                                                                                                                                                                              
x_up = np.random.random(size=(30,))                                                                                                                                                           
x_down = np.random.random(size=(30,))

noise = 0.03

y_down = np.cos(x_down * 4) + noise * np.random.randn(*x_down.shape)
y_up = np.cos(x_up * 4) + np.sin(x_up) ** 2 + noise * np.random.randn(*x_up.shape)

x = np.concatenate((x_down, x_up))
y = np.concatenate((y_down, y_up))[:, np.newaxis]

bsearch = np.linspace(0, 1, num=20).tolist()

global_branching = np.concatenate((np.full(x_up.shape, fill_value=3), np.full(x_down.shape, fill_value=2)))
global_branching[x < 0.2] = 1

model = BranchedGP.FitBranchingModel.FitModel(bsearch, x, y, global_branching, M=10, maxiter=20)

plt.figure()
plt.subplot(211)
plt.scatter(x, y[:, 0])

plt.vlines(bsearch, -1, 1, color='k', alpha=0.2)
plt.axvline(bsearch[model['loglik'].argmax()])

plt.subplot(212)
plt.plot(bsearch, model['loglik'])

plt.show()
```
![branching](https://user-images.githubusercontent.com/1616942/58283123-d77fd400-7da7-11e9-8b41-285ece87478c.png)

**Comment by magnusrattray** [comment]
Interesting example - I suppose that as you sample time more densely you will be able to identify the branching earlier and earlier.

**Comment by Dapid** [comment]
@magnusrattray it doesn't seem that way. Here is with double the points, the branching position is in the same location:

![branched](https://user-images.githubusercontent.com/1616942/58483946-6fdbd700-8161-11e9-9a6e-28343ad659a2.png)

I am a bit uncertain about my usage of `global_branching`, since the example is tightly tied to Monocle, and I am not familiar with that.

**Comment by jyangUK** [comment]
Is it because the branching results will depend on if you choose MAP,
median or mean to present your branching results?

**Comment by magnusrattray** [comment]
Well the posterior mean is certainly to the left of the MAP branching point because there is significant posterior mass on the left, but I'm a bit surprised that the MAP doesn't agree with where I would choose it by eye. We'll run it and have a look.
